apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-shortener-pvc-sample
  namespace: url-shortener
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-standard
  resources:
    requests:
      storage: 10Gi
# This sample PVC is provided for operators who prefer static PVCs outside StatefulSets
